AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.3

inherit_from:
  - .rubocop-rails.yml

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/IndentationConsistency:
  EnforcedStyle: normal
